# Generated by Django 3.1.7 on 2021-02-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210224_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
